"""Extract the citizen-facing Kannada strings into a review sheet.

"A native speaker should check this" is not an actionable instruction. This
turns it into one: every string a member of the public can read, English beside
Kannada, ordered so the safety and legal text comes first. Hand docs/KANNADA_REVIEW.md
to a Kannada speaker and it is a ten-minute job.

Regenerate after touching any report.* or reportStatus.* key:
    python gen_kn_review.py
"""
import io
import re

SRC = "frontend/src/lib/i18n.tsx"
OUT = "docs/KANNADA_REVIEW.md"

# Ordered: the strings where a mistranslation has consequences come first.
PRIORITY = [
    ("Safety and legal — a mistranslation here has real consequences", [
        "report.emergency.title", "report.emergency.body",
        "report.blocked.title", "report.blocked.body",
        "report.consent",
        "report.severity.emergency", "report.severity.urgent", "report.severity.routine",
        "report.demoBanner",
    ]),
    ("What the reporter is asked for", [
        "report.title", "report.lede", "report.stamp",
        "report.step.what", "report.step.where", "report.step.verify",
        "report.category.label", "report.category.placeholder",
        "report.severity.label",
        "report.description.label", "report.description.hint", "report.description.placeholder",
        "report.when.label", "report.district.label",
        "report.location.label", "report.location.hint",
        "report.location.useGps", "report.location.gpsFailed",
        "report.email.label", "report.email.hint",
        "report.otp.send", "report.otp.label", "report.otp.demoHint",
        "report.otp.verify", "report.otp.verified",
        "report.submit", "report.submitting", "report.emergency.back",
    ]),
    ("What the reporter is told afterwards", [
        "report.done.title", "report.done.refLabel", "report.done.body",
        "report.done.dup", "report.done.track", "report.done.another",
        "reportStatus.stamp", "reportStatus.title", "reportStatus.lede",
        "reportStatus.signInFirst", "reportStatus.mine", "reportStatus.none",
        "reportStatus.filed", "reportStatus.updated", "reportStatus.timeline",
        "reportStatus.withdraw", "reportStatus.reply", "reportStatus.send",
    ]),
    ("Status names the reporter sees on their own report", [
        "rstatus.SUBMITTED", "rstatus.TRIAGE", "rstatus.NEEDS_INFO",
        "rstatus.DUPLICATE", "rstatus.REJECTED", "rstatus.VERIFIED_FIR",
        "rstatus.CLOSED_NO_ACTION", "rstatus.WITHDRAWN",
    ]),
    ("Reasons shown to the reporter for a decision", [
        "reason.insufficient_detail", "reason.outside_jurisdiction", "reason.duplicate_of",
        "reason.not_a_crime", "reason.unverifiable", "reason.no_response",
        "reason.verified_on_site", "reason.referred_elsewhere", "reason.supervisor_reopen",
    ]),
    ("Errors the reporter can hit", [
        "report.err.RATE_LIMITED", "report.err.OTP_INVALID", "report.err.OTP_EXPIRED",
        "report.err.OTP_ATTEMPTS", "report.err.UNAUTHENTICATED", "report.err.FORBIDDEN",
        "report.err.NOT_FOUND", "report.err.VALIDATION", "report.err.BLOCKED",
        "report.err.SEALED", "report.err.ILLEGAL_TRANSITION",
        "report.err.ATTACHMENT_TOO_LARGE", "report.err.ATTACHMENT_TYPE",
        "report.err.OFFLINE", "report.err.SERVER",
    ]),
]

src = io.open(SRC, encoding="utf-8").read()


def lookup(key):
    """Return (en, kn) for a key, handling both the one-line and block forms."""
    esc = re.escape(key)
    pat = (r"'" + esc + r"':\s*\{\s*en:\s*'((?:[^'\\]|\\.)*)'\s*,\s*"
           r"kn:\s*'((?:[^'\\]|\\.)*)'\s*,?\s*\}")
    m = re.search(pat, src, re.S)
    if m:
        return m.group(1), m.group(2)
    return None, None


lines = [
    "# Kannada review sheet — citizen-facing strings",
    "",
    "Generated by `gen_kn_review.py` from `frontend/src/lib/i18n.tsx`.",
    "",
    "Every string below is readable by a member of the public using the report",
    "portal. The grammar has been checked, but none of it has been signed off by a",
    "native Kannada speaker. **That sign-off is a release blocker, not a nicety** —",
    "the first section in particular tells someone whether to wait for a reply or",
    "dial 112.",
    "",
    "For each row: does the Kannada say what the English says, and would a Kannada",
    "speaker in Karnataka phrase it that way? Note anything that reads as machine",
    "translation, is too formal, or is ambiguous.",
    "",
]

missing = []
total = 0
for heading, keys in PRIORITY:
    lines += ["---", "", f"## {heading}", ""]
    for key in keys:
        en, kn = lookup(key)
        if en is None:
            missing.append(key)
            continue
        total += 1
        lines += [
            f"**`{key}`**",
            "",
            f"- EN — {en}",
            f"- KN — {kn}",
            "- [ ] reads correctly",
            "",
        ]

lines += [
    "---",
    "",
    "## Known exclusions",
    "",
    "These deliberately stay in Latin script and are not translation errors:",
    "acronyms (FIR, IPC, STL, ILP, SHAP, Gi\\*), the reference-number prefix `PR-`,",
    "person names from the FIR record, and basemap attribution.",
    "",
]

io.open(OUT, "w", encoding="utf-8").write("\n".join(lines))
print("wrote %s — %d strings across %d sections" % (OUT, total, len(PRIORITY)))
if missing:
    print("MISSING (key not found in i18n.tsx): %s" % ", ".join(missing))
